# Toggle metrics to use them (true/false).
# Do NOT delete entries

metrics:
# CPU
  rouge1: false
  rouge2: false
  autosummeng: false
  memog: false
  npower: false
# GPU
  bertscore: false
  bartscore: false
  bleurt: false
  factcc: false
  ldfactscore: false
  finsumeval: true
